import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import StoreProvider from "@/store/storeprovider";
import Footer from "./components/Footer";

const poppins = Poppins({
  subsets: ["latin", "latin-ext", "devanagari"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={poppins.className}>
          <header>
            <Navbar />
          </header>

          {/* main page content */}
          {children}
          {/* footer component */}
          <Footer/>
        </body>
      </html>
    </StoreProvider>
  );
}
