export const USER_REPOSITORY = 'USER_REPOSITORY';
export const REFRESH_TOKEN_REPOSITORY = 'REFRESH_TOKEN_REPOSITORY';
export const DEVICE_TOKEN_REPOSITORY = 'DEVICE_TOKEN_REPOSITORY';
export const HASH_SERVICE = 'HASH_SERVICE';
export const TOKEN_SERVICE = 'TOKEN_SERVICE';
