import type { Metadata } from "next";
import { Suspense } from "react";

import "@/app/globals.css";

import Hero from "@/app/components/dynamic-course/Hero";
import SideBar from "@/app/components/dynamic-course/SideBar";
import SideHeading from "@/app/components/dynamic-course/SideHeading";
import { CourseHeroSkeleton } from "@/app/components/Skeletons";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: { courseId: string; contentId: string; moduleId: string };
}) {
  return (
    <main className="bg-Tertiary">
      {/* hero section that has details of the course */}
      <Suspense fallback={<CourseHeroSkeleton />}>
        <Hero id={params.courseId} />
      </Suspense>

      {/* heading that controls sidebar toggle */}
      <SideHeading />

      {/* section with course content */}
      <section className="xl:flex xl:min-h-[80vh] pb-5">
        {/* sidebar to navigate between sub-courses */}
        <SideBar />

        {/* course content like video */}
        <div className="xl:border-l-2 w-full">{children}</div>
      </section>
    </main>
  );
}
